# Generated by Django 4.2.6 on 2023-10-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi_pertanyaan', models.TextField()),
                ('isi_jawaban', models.TextField()),
            ],
        ),
    ]
