# Generated by Django 4.2.6 on 2023-10-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0003_question_judul_buku_questionanswer_judul_buku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='judul_buku',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='judul_buku',
        ),
        migrations.AddField(
            model_name='question',
            name='id_buku',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='id_buku',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
