# Generated by Django 4.2.6 on 2023-10-27 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinjamBuku', '0002_auto_20231024_2352'),
        ('FAQ', '0004_remove_question_judul_buku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id_buku',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='id_buku',
        ),
        migrations.AddField(
            model_name='question',
            name='buku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pinjamBuku.buku'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='buku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pinjamBuku.buku'),
            preserve_default=False,
        ),
    ]
