# Generated by Django 4.2.6 on 2023-10-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0005_remove_question_id_buku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='isi_pertanyaan',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='isi_jawaban',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='isi_pertanyaan',
            field=models.CharField(max_length=255),
        ),
    ]
