# Generated by Django 4.2.4 on 2023-10-28 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinjamBuku', '0002_auto_20231024_2352'),
        ('ulasanBuku', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.RemoveField(
            model_name='review',
            name='prof_pict',
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pinjamBuku.buku'),
            preserve_default=False,
        ),
    ]
