# Generated by Django 4.2.6 on 2023-10-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilUser', '0004_favorit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorit',
            name='buku',
        ),
        migrations.AddField(
            model_name='favorit',
            name='authors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favorit',
            name='id_book',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favorit',
            name='language_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favorit',
            name='num_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favorit',
            name='publication_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favorit',
            name='publisher',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favorit',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
