# Generated by Django 4.2.6 on 2023-10-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilUser', '0005_remove_favorit_buku_favorit_authors_favorit_id_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorit',
            name='id_book',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
