# Generated by Django 4.2.6 on 2023-10-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilUser', '0007_remove_userprofile_name_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='status',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='foto_profil',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='Reguler', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tanggal_lahir',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
