# Generated by Django 4.2.6 on 2023-10-29 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pinjamBuku', '0002_auto_20231024_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pinjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('id_book', models.IntegerField()),
                ('authors', models.TextField(blank=True, null=True)),
                ('language_code', models.TextField(blank=True, null=True)),
                ('num_pages', models.IntegerField(blank=True, null=True)),
                ('publication_date', models.TextField(blank=True, null=True)),
                ('publisher', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
