# Generated by Django 4.2.6 on 2023-10-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithrole',
            name='role',
            field=models.CharField(choices=[('Reguler', 'Reguler'), ('Special', 'Special')], max_length=10),
        ),
    ]
