# Generated by Django 4.2.6 on 2023-10-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userwithrole_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwithrole',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
